version: '3.3'
services:
    web:
        container_name: "web-nginx"    
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
        volumes:
            - "~/bi/web:/var/www/web/bi"
            - "~/bi/logs_nginx/error:/var/log/nginx/error/"
            - "~/bi/logs_nginx/access:/var/log/nginx/access/"
            - "./default.conf:/etc/nginx/conf.d/default.conf"
        links:
            - php
    php:
        container_name: "web-php"    
        build: php-build
        restart: always
        env_file:
            - bi.env
        environment:
            API_PATH: /bi
            GIT_URL: gitlab.com
            GIT_BRANCH: BIWeb
            GIT_ACCOUNT: hookapi_bm
            GIT_PASSWORD: glpat-J9e5zd87dFVHDUpx_yGf            
        volumes:
            - ~/bi/web:/var/www/web/bi
            - ~/bi:/bi            
            - "./entrypoint.sh:/entrypoint.sh"            
            - "~/web/logs/bi/logs:/var/www/web/bi/logs"
            - "~/web/logs/bi/smarty2/admin_lte3/templates_c:/var/www/web/bi/views/smarty2/admin_lte3/templates_c"

