version: '3.3'
services:
    web:
        container_name: "api-nginx"
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
        volumes:
            - "~/api/web:/var/www/html"
            - "./default.conf:/etc/nginx/conf.d/default.conf"
            - "~/api/logs_nginx/error:/var/log/nginx/error/"
            - "~/api/logs_nginx/access:/var/log/nginx/access/"
        links:
            - php
    php:
        container_name: "bloxmith-api-php"
        build: php-build
        restart: always
        env_file:
            - bloxmith.env        
        environment:
            API_PATH: /api
            GIT_URL: gitlab.com/pumpkinstudio/blockraidersserver
            GIT_BRANCH: BIAPI
            GIT_ACCOUNT: hookapi_bm
            GIT_PASSWORD: glpat-J9e5zd87dFVHDUpx_yGf
        volumes:
            - "~/api:/api"
            - "~/api/web:/var/www/html"
            - "./entrypoint.sh:/entrypoint.sh"
