version: '3.3'
services:
    web:
        image: nginx:latest
        restart: always
        ports:
            - "8203:80"
        volumes:
            - "~/web/bloxmith_api:/var/www/html"
            - "./default.conf:/etc/nginx/conf.d/default.conf"
            - "~/web/logs/bloxmith_api/error:/var/log/nginx/error/"
            - "~/web/logs/bloxmith_api/access:/var/log/nginx/access/"
        links:
            - php
    php:
        build: php-build
        restart: always
        volumes:
            - "~/web/bloxmith_api:/var/www/html"
            - "~/web/logs/bloxmith_api/storage:/var/www/html/storage"

        extra_hosts:
            - "db1s:172.17.82.19"
            - "db1m:172.17.82.20"
